name: Build, Test

on:
 push:
   branches:
     - master
 workflow_dispatch:
   branches:
     - master

jobs:
  phpunit-all:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        uses: php-actions/composer@v6

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Run tests
        uses: php-actions/composer@v6
        with:
          version: 2
          command: test

