name: Build, Deploy

on:
 push:
   branches:
     - master
 workflow_dispatch:
   branches:
     - master

jobs:
  phpunit-all:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        uses: php-actions/composer@v6

      - name: Run tests
        uses: php-actions/composer@v6
        with:
          command: test

