name: Aries Container Tests
# https://docs.github.com/en/actions/using-containerized-services/about-service-containers

on:
 push:
   branches:
     - master
 workflow_dispatch:
   branches:
     - master

jobs:
  start-aries-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull images and setup network
        run: |
          docker pull ghcr.io/hyperledger/aries-framework-go:0.1.8
          docker network create --label kraken-network github_network_kraken


      - name: Create student container
        run: |
          docker create --name student-agent-container --label student-agent --network github_network_kraken --network-alias student-agent -p 8092:8092 -p 8091:8091  -e "ARIESD_API_HOST=0.0.0.0:8092" -e "ARIESD_INBOUND_HOST=http@0.0.0.0:8091" -e "ARIESD_INBOUND_HOST_EXTERNAL=http@http://student-agent:8091" -e "ARIESD_WEBHOOK_URL=https://enybebk8mydni.x.pipedream.net" -e "ARIESD_DEFAULT_LABEL=student-agent" -e "ARIESD_DATABASE_TYPE=leveldb" -e "ARIESD_DATABASE_PREFIX=data/student" -e "ARIESD_DATABASE_TIMEOUT=60" -e "ARIESD_HTTP_RESOLVER=web@https://resolver.prod.ari-bip.eu/1.0/identifiers,elem@https://resolver.prod.ari-bip.eu/1.0/identifiers,ebsi@https://resolver.prod.ari-bip.eu/1.0/identifiers" -e "ARIESD_CONTEXT_PROVIDER_URL=https://context.prod.ari-bip.eu/agent-startup-contexts.json" -e GITHUB_ACTIONS=true -e CI=true ghcr.io/hyperledger/aries-framework-go:0.1.8 start
          docker start student-agent-container


      - name: Create university container
        run: |
          docker create --name university-agent-container --label university-agent --network github_network_kraken --network-alias university-agent -p 8082:8082 -p 8081:8081  -e "ARIESD_API_HOST=0.0.0.0:8082" -e "ARIESD_INBOUND_HOST=http@0.0.0.0:8081" -e "ARIESD_INBOUND_HOST_EXTERNAL=http@http://university-agent:8081" -e "ARIESD_WEBHOOK_URL=https://enybebk8mydni.x.pipedream.net" -e "ARIESD_DEFAULT_LABEL=university-agent" -e "ARIESD_DATABASE_TYPE=leveldb" -e "ARIESD_DATABASE_PREFIX=data/university" -e "ARIESD_DATABASE_TIMEOUT=60" -e "ARIESD_HTTP_RESOLVER=web@https://resolver.prod.ari-bip.eu/1.0/identifiers,elem@https://resolver.prod.ari-bip.eu/1.0/identifiers,ebsi@https://resolver.prod.ari-bip.eu/1.0/identifiers" -e "ARIESD_CONTEXT_PROVIDER_URL=https://context.prod.ari-bip.eu/agent-startup-contexts.json" -e GITHUB_ACTIONS=true -e CI=true ghcr.io/hyperledger/aries-framework-go:0.1.8 start
          docker start university-agent-container


      - name: Show service logs
        continue-on-error: true
        run: |
          docker ps
          docker logs "student-agent-container"
          docker logs "university-agent-container"

      - name: Give agents time to start ...
        continue-on-error: true
        run: |
          sleep 60

      - name: Test uni connection via localhost
        continue-on-error: true
        run: |
          curl http://localhost:8082/connections
          docker logs "university-agent-container"


      - name: Test uni connection via 127.0.0.1
        continue-on-error: true
        run: |
          curl http://127.0.0.1:8082/connections
          docker logs "university-agent-container"

      - name: Test student connection via localhost
        continue-on-error: true
        run: |
          curl http://localhost:8092/connections
          docker logs "student-agent-container"


      - name: Test student connection via 127.0.0.1
        continue-on-error: true
        run: |
          curl http://127.0.0.1:8092/connections
          docker logs "student-agent-container"

      - name: Init Aries KMS
        continue-on-error: true
        run: |
          pip3 install requests
          python3 .github/helper/kms_init.py

      # -
      #   name: Test via hostname
      #   continue-on-error: true
      #   run: |
      #     curl http://student-agent:8092/connections
